### PR TITLE
uml: lookup path

### PR DESCRIPTION
**Pull request by gportay**
Hello,

Most distros ship the binaries at different path locations.

This PR intends to make the UML backend less distro-specific by lookup the binaries in a hardcoded list of known locations.

Better idea?

Best Regards,
Gaël

### CODE REVIEW

**Comment by evelikov** [comment]
The MR changes things in backward incompatible manner - `/usr/lib/uml/modules` magically becomes `/usr/lib/modules/uml`

**Comment by gportay** [comment]
> The MR changes things in backward incompatible manner - `/usr/lib/uml/modules` magically becomes `/usr/lib/modules/uml`

Oops :facepalm:

Fixed

**Comment by evelikov** [comment]
UML is very low on my priority list, since there's no official support in Arch. Will get to it eventually though.

**Comment by obbardc** [comment]
Moving this forward as part of #112 so closing in favour of that PR.

**Pull request closed without merging**
