### PR TITLE
Accept Qemu options from commandline

### PR DESCRIPTION
**Pull request by Lakshmipathi**
Accept additional Qemu options from commandline. Sample usage:

 `fakemachine --qemuopts="-display sdl,gl=on -vga virtio -serial mon:stdio"` 

Signed-off-by: Lakshmipathi.G <lakshmipathi.ganapathi@collabora.co.uk>

### CODE REVIEW

**Comment by sjoerdsimons** [comment]
@Lakshmipathi the git history for this PR is rather weird? Looks like you did a merge commit at some point. Could you clean it up and resubmit?

**Comment by Lakshmipathi** [comment]
@sjoerdsimons okay, please ignore this PR, will send a clean/new PR.

**Comment by Lakshmipathi** [comment]
okay, updated this PR

**Comment by Lakshmipathi** [comment]
Will send a new PR , closing this.

**Pull request closed without merging**
