### PR TITLE
Accept Qemu options from commandline

### PR DESCRIPTION
**Pull request by Lakshmipathi**
Pass custom qemu options while launching fakemachine.

Sample usage:
By default fakemachine starts Qemu with '-display none', we
can modify it by passing below option,

qemuopts='-display sdl,gl=es'

Signed-off-by: Lakshmipathi.G <lakshmipathi.ganapathi@collabora.co.uk>

### CODE REVIEW

**Comment by smcv** [comment]
Does qemu (guarantee to) interpret `qemu-system-x86_64 -display none -display sdl` as being equivalent to `qemu-system-x86_64 -display sdl`?

**Comment by Lakshmipathi** [comment]
Yes, I think so ` qemu-system-x86_64 -display none -display curses` overrides `none` and launches qemu with ncurses.

**Comment by Lakshmipathi** [comment]
@sjoerd-ccu If this looks fine, can you merge it and close this PR?

**Comment by sjoerdsimons** [comment]
@Lakshmipathi I'm rather on the fence about this one still; Is this something you're still interested in ?

**Comment by Lakshmipathi** [comment]
@sjoerdsimons, This change looked useful at the time, but until now no-one seems to be blocked because this missing option. May be we can drop this change.

**Pull request closed without merging**
