### PR TITLE
Initialise as go module

### PR DESCRIPTION
**Pull request by obbardc**
Switch to using go modules and our fork of a specific library.

cc @evelikov-work @evelikov

### CODE REVIEW

**Comment by evelikov-work** [comment]
Aside: I would encourage you to put a bit more meat/context into the commit messages - feel free to reuse any of https://github.com/go-debos/fakemachine/pull/63.

**Comment by obbardc** [comment]
> * forking gocpio - unfortunate but it helps us move forward

Yeah - hopefully we can get in touch with upstream to sort things out ;-).

> * using go modules - happy to see alas @sjoerdsimons had concerns
> IIRC his main point was that the upper version is fixed, so we need to (semi)-manually update the go modules every so often.

Yeah, I think dependabot's automatic will help us here ;-)
Although since we do not bump fakemachine's version the debos gomod will need some help.

> Aside: I would encourage you to put a bit more meat/context into the commit messages - feel free to reuse any of #63.

ack, will do. How do you want me to attribute you in the gomod commit, since it's basically your work ?

**Comment by evelikov-work** [comment]
> Yeah, I think dependabot's automatic will help us here ;-) Although since we do not bump fakemachine's version the debos gomod will need some help.
> 

Sounds like a plan - mind you it can get _very_ spamy. Hope that Sjoerd is ok with it.

> 
> ack, will do. How do you want me to attribute you in the gomod commit, since it's basically your work ?

Would be great, thanks.

**Comment by obbardc** [comment]
closing in favour of !63
sorry for the noise

**Pull request closed without merging**
