### PR TITLE
Add a man page

### PR DESCRIPTION
**Pull request by obbardc**
During the latest Debian package update, lintian warned that no manual page for fakemachine exists. Add a manual page so that the next import closes this warning.

### CODE REVIEW

**Comment by evelikov** [comment]
What's the reason behind having the generated artefacts in git? I've seen many projects avoid that and only a few that do.

**Comment by obbardc** [comment]
> What's the reason behind having the generated artefacts in git? I've seen many projects avoid that and only a few that do.

Really at this point it's to have unity with debos and get a man page generated. It's one less thing to do at release time too. I have no preference ;-).

**Comment by sjoerdsimons** [comment]
would be nice to improve and not have the man page in git in future at least; but ok for now

**Comment by obbardc** [comment]
Bors retry

**Comment by obbardc** [comment]
bors retry

**Pull request merged**
